//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSync.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobSync.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos uma letra maiúscula (A-Z).
        /// </summary>
        public static string AZ_MAIUSCULO {
            get {
                return ResourceManager.GetString("AZ_MAIUSCULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos uma letra minúscula (a-z).
        /// </summary>
        public static string AZ_MINUSCULO {
            get {
                return ResourceManager.GetString("AZ_MINUSCULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos um caractere especial (ex: !@#$%).
        /// </summary>
        public static string CARACTER_ESPECIAL {
            get {
                return ResourceManager.GetString("CARACTER_ESPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF informado é inválido (número repetido).
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF informado não é válido.
        /// </summary>
        public static string CPF_NAO_EXISTE {
            get {
                return ResourceManager.GetString("CPF_NAO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório e deve conter 11 dígitos.
        /// </summary>
        public static string CPF_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CPF_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse email não existe.
        /// </summary>
        public static string EMAIL_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("EMAIL_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email vazio.
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário conter Email.
        /// </summary>
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero inválido.
        /// </summary>
        public static string GENDER_INVALID {
            get {
                return ResourceManager.GetString("GENDER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor informe seu gênero.
        /// </summary>
        public static string GENDER_REQUIRED {
            get {
                return ResourceManager.GetString("GENDER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha ou email inválido.
        /// </summary>
        public static string INVALID_PASSWORD_OR_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD_OR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode ser menor que 8 dígitos.
        /// </summary>
        public static string MENOR_QUE_OITO {
            get {
                return ResourceManager.GetString("MENOR_QUE_OITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome vazio.
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone nulo.
        /// </summary>
        public static string NULL_PHONE {
            get {
                return ResourceManager.GetString("NULL_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número inválido.
        /// </summary>
        public static string NUMBER_INVALID {
            get {
                return ResourceManager.GetString("NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos um número (0-9).
        /// </summary>
        public static string NUMERO_ZERO_A_NOVE {
            get {
                return ResourceManager.GetString("NUMERO_ZERO_A_NOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse telefone não existe.
        /// </summary>
        public static string PHONE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("PHONE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário conter número de Telefone.
        /// </summary>
        public static string PHONE_NUMBER_REQUIRED {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode ser nula.
        /// </summary>
        public static string SENHA_NULA {
            get {
                return ResourceManager.GetString("SENHA_NULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone vazio.
        /// </summary>
        public static string TELEFONE_EMPTY {
            get {
                return ResourceManager.GetString("TELEFONE_EMPTY", resourceCulture);
            }
        }
    }
}
